### ISSUE TITLE
Inconsistent API of django's EmailBackend._send

### ISSUE THREAD

**Issue by sjoerdjob-legalsense** [themartorana/python-postmark#105]
Hi! In #89 , `_send` was changed to return a tuple, and `send_messages` was updated to expect a tuple.

However: looking at https://github.com/themartorana/python-postmark/pull/89/files#diff-0a79263ddca0f892c07ae4bdfe5201366d5e7dd9b0fc7d23be8937a1b9dce1edR142 we see that there are still cases where the `_send` method returns a single boolean instead of a tuple of a boolean together with a list of messages. This then causes a TypeError in `send_messages`.

**Comment by nicholasserra** [comment]
Good catch. I'll get a patch and new version up asap. Sounds like we're missing some test coverage.

**Comment by nicholasserra** [comment]
Fix in https://github.com/themartorana/python-postmark/pull/106
