### ISSUE TITLE
PMMail.send() doesn't return MessageID

### ISSUE THREAD

**Issue by mkotsalainen** [themartorana/python-postmark#18]
Postmark returns a json document containing the MessageID of the recently submitted email. PMMail.send() just returns True if all went well. Wouldn't it be better to return the MessageID if things went well?! This MessageID is necessary when writing a bouncehook: http://developer.postmarkapp.com/developer-bounces.html#bounce-hooks

**Comment by nicholasserra** [comment]
Should be able to access `message_id` attribute of the `PMMail` instance once the send has happened.
