### ISSUE TITLE
Attachments broken in Python 2.6 as of merge with 'joshourisman/master' 

### ISSUE THREAD

**Issue by brimcfadden** [themartorana/python-postmark#2]
I'm running Python 2.6.5 (version in the Ubuntu repository) on Ubuntu 10.04. Here is the traceback.

    Traceback (most recent call last):
      File "./postmark_demo.py", line 24, in <module>
        pmm.send()
      File "/usr/local/lib/python2.6/dist-packages/postmark/core.py", line 350, in send
        elif isinstance(attachment, email.mime.base.MIMEBase):
    AttributeError: 'module' object has no attribute 'base'

The module, for whatever reason (Python packages are still a bit weird to me), isn't accessible when just `email` is imported. If the module is imported at the top as `email.mime.base` instead of as `email`, this problem would be fixed without even needing to change line 350. The `email` module isn't used anywhere else in this file, so I don't think it would be an issue.

[I also had a question which I have since answered.]

**Comment by nicholasserra** [comment]
Fixed in #3
