### ISSUE TITLE
Postmark and Sentry, sitting in a tree ...

### ISSUE THREAD

**Issue by stateempire** [themartorana/python-postmark#23]
Heya, I've got Sentry reporting running on it's own Arch Linux server, quite happily. But when I add the Postmark details to the "/etc/sentry.conf.py" using python-postmark it simply has no idea what's going on, I'm not getting any errors but no mails are getting through, or test results. 

Any ideas would be amazing:

Contents of "/etc/sentry.conf.py":

EMAIL_BACKEND = 'postmark.django_backend.EmailBackend'
SERVER_EMAIL = 'xxx@yyy.com'
POSTMARK_API_KEY = 'API_KEY'
POSTMARK_SENDER = 'xxx@yyy.com'
POSTMARK_TEST_MODE = False

Cheers,

d.

**Comment by nicholasserra** [comment]
This is pretty old, and I'm guessing a lot has changed in Sentry since then. FWIW I've been seeing postmark errors in Sentry consistently for years, so it was probably a config issue.
