### ISSUE TITLE
support inline images

### ISSUE THREAD

**Issue by hsurreal** [themartorana/python-postmark#47]
The API appears to support a ContentID being specified in an attachment. However, the current version of python-postmark does not appear to pass this through when setting attachments.

**Comment by butorov** [comment]
+1
And I had a problem with the lack of exceptions when trying to send such a letter.

**Comment by gduverger** [comment]
+1

**Comment by TiO2** [comment]
+1  The inline images will be nice for html templates with images. I guess it will not be difficult to add? The to_json_method now have parsing for "name","content" and "ContentType". It can add the "ContentID" field for inline images?

**Comment by nicholasserra** [comment]
Fixed in #64
