### ISSUE TITLE
Unprocessable Entity: Received valid, but incompatible JSON input

### ISSUE THREAD

**Issue by lexbryan** [themartorana/python-postmark#50]
we always get this error but the email was successful.
```python
lib.postmark.core.PMMailUnprocessableEntityException: 'Unprocessable Entity: Received valid, but incompatible JSON input.'
```

this is the sample output when I printed after self.to_json_message was executed.

```python
{'From': 'support@example.com', 'HtmlBody': 'Reports Sent (v4): 1', 'ReplyTo': 'sent_reports_report@example.com', 'TextBody': 'Reports Sent (v4): 1', 'To': ['admin1@example.com', 'admin2@gmail.com', 'admin3@example.com'], 'Subject': 'Reports Sent (v4): 1'}
```
hope you can help.. thanks.

**Comment by orlandobrent** [comment]
I was having the same problem earlier today, and it turned out to be a simple mistake on my part. You need to pass in a string of comma separated email addresses for "To", not a List of them. 
'To': "admin1@example.com,admin2@gmail.com,admin3@example.com"

**Comment by lexbryan** [comment]
yep we figured that out as well.

thanks.

**Comment by themartorana** [comment]
@lexbryan @orlandobrent does it make sense to accept either? We can type-check and accept either a string or list...?

**Comment by orlandobrent** [comment]
@themartorana I'm using Django and it does use lists for its recipients, so adding list support would be very nice! It looks like #35  is already requesting that too.

**Comment by themartorana** [comment]
Good catch. Moving to #35
