### ISSUE TITLE
MessageID accessible via Django Backend

### ISSUE THREAD

**Issue by adityarustgi** [themartorana/python-postmark#59]
Looking at the code, it seems that if we directly use the PMMail object, we can get access to the MessageID of the resulting message.

However, when you use the PMEmailMessage.send, then there is no way of accessing the PMEmailMessage, because the code doesn't populate the MessageId back on this object.

thoughts?

**Comment by nicholasserra** [comment]
I think the message id would be nice to have after it's sent, PRs are welcome :)

**Comment by nicholasserra** [comment]
Fixed in #89
