### ISSUE TITLE
Sending out emails with special characters (like Chinese characters)

### ISSUE THREAD

**Issue by bendtheji** [themartorana/python-postmark#60]
Hi,

I would like to enquire how the API deals with sending out emails with special characters inside the attributes. For example, currently I'm trying to send out an email whereby using the PMMail Object, I'm passing in this unicode value "u'\u7f2a\u5efa\u5175'" into the to attribute of the PMMail object. The value is supposed to be chinese characters. I sent the object to my own email and received the message with the chinese characters displayed, however I also get this error:
"An unknown error occured: 'ascii' codec can't decode byte 0xe7 in position 7: ordinal not in range(128)"

I tried changing a bit of the code for core.py on line 449

Original:
jsontxt = result.read().decode()

Edited:
jsontxt = result.read().decode('utf8')

The email sends out and gives me the chinese characters and also there is no error displayed. 
What do you think?

**Comment by nicholasserra** [comment]
Do you have a full traceback?

**Comment by bendtheji** [comment]
Here's a PMMail object formed with the PMMail object constructor in core.py

mail_object = PMMail(api_key="871d7c30-6479-499e-b4f6-37c2dabd0860", sender="chinab <kevin.jublia@terrapinn.com>", to=chinese + "<benjsoon2@gmail.com>",cc="",subject="give me problems please", html_body="hwnvqonv",track_opens=True,attachments=[],reply_to="kevin.jublia@terrapinn.com")

and the chinese variable contains:
u'\u7f2a\u5efa\u5175'

The mail_object is created and now I try to send it with the send function:
r = mail_object.send()


And I got this error:
UnicodeDecodeError                        Traceback (most recent call last)
<ipython-input-11-5a2d27b0a934> in <module>()
----> 1 r = mail_object.send()

/home/ubuntu/process/app/util/postmarkcore.pyc in send(self, test)
    448             result = urlopen(req)
    449 
--> 450             jsontxt = result.read().decode()
    451             #except UnicodeError as e:
    452             #    print e

UnicodeDecodeError: 'ascii' codec can't decode byte 0xe7 in position 7: ordinal not in range(128)

I just rewrote postmarkcore.py a little with spaces and comments, it's basically like the core.py file in the API

**Comment by nicholasserra** [comment]
Fixed in #61
