### ISSUE TITLE
PMBounceManager.activate uses non-existent `HTTPConnection`

### ISSUE THREAD

**Issue by teeberg** [themartorana/python-postmark#69]
```
  File ".../.venv/lib/python2.7/site-packages/postmark/core.py", line 875, in activate
    h1 = HTTPConnection('api.postmarkapp.com')
NameError: global name 'HTTPConnection' is not defined
```
Python 2.7.13. Seems to be the only place in that file that uses this class.

**Comment by nicholasserra** [comment]
Hello, thanks for the report. Seems we have some issues with our import chain with 2.7.13. Will try to sort that out asap.

**Comment by teeberg** [comment]
Thank you for the quick fix!

**Comment by nicholasserra** [comment]
Welcome! Let me know if you need this to go out to pypi asap, otherwise it will go out with next release.

**Comment by teeberg** [comment]
I'm currently sending the request myself manually using `requests.put`, so it's not urgent for me :) When do you plan to have the next release?

**Comment by nicholasserra** [comment]
No idea to be honest. Maybe after a couple more patches land.
