### ISSUE TITLE
Provide a MessageStream parameter

### ISSUE THREAD

**Issue by cel03** [themartorana/python-postmark#92]
### **Postmark service**  
Postmark API supports to set a MessageStream which the e-mail must be sent througth.
- API Interface: https://postmarkapp.com/developer/api/email-api
- MessageStream Presentation: https://postmarkapp.com/message-streams

### **Use case**
A use case is to allow users that send only transactional e-mail use the MessageStream dedicated for it.

### **Proposal** 
Python-postmark should provide a "message_stream" string parameter that allows to set which MessageStream to use.

**Comment by nicholasserra** [comment]
Thanks for the suggestion. Seems like a simple patch to get this in. PRs welcome! Otherwise I probably won't pick this up myself for a while.

**Comment by anulaibar** [comment]
@nicholasserra Any release planned with #94 ?

**Comment by nicholasserra** [comment]
I'll try to get a release out this week

**Comment by nicholasserra** [comment]
0.5.6 released
