### ISSUE TITLE
[Question] Changes to Postmark TLS config

### ISSUE THREAD

**Issue by gadybadger** [themartorana/python-postmark#95]
Do you happen to know if python-postmark will be affected by the [upcoming TLS changes](https://postmarkapp.com/updates/upcoming-tls-configuration-changes-for-api-users-action-may-be-required) Postmark is making to their API? From what I can tell, nothing in python-postmark should be affected, but I wanted to get a sanity check on that.

Thanks much!!

**Comment by nicholasserra** [comment]
Yup, this package just uses standard python utilities like urllib, so nothing in here needs updated. Everything should be fine upstream. Thanks!
